# Generated by Django 5.0 on 2025-10-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_application_email_job_employer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='email_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
