# Generated by Django 5.0 on 2025-11-23 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_message_email_failed_message_email_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='jobs.job')),
            ],
            options={
                'ordering': ['job', 'order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_moved', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this candidate')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='jobs.application')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.pipelinestage')),
                ('previous_stages', models.ManyToManyField(blank=True, related_name='moved_from_applicants', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['-date_moved'],
            },
        ),
        migrations.CreateModel(
            name='PipelineTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='jobs.applicantpipeline')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='jobs.pipelinestage')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_moves', to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
