# Generated by Django 5.1.12 on 2025-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='professional_summary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_contact_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_recruiters_to_contact',
            field=models.BooleanField(default=False, help_text='Allow recruiters to contact you'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Your education background', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Your work experience', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Your skills (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_privacy',
            field=models.CharField(choices=[('public', 'Public - Visible to all recruiters'), ('private', 'Private - Only visible to you')], default='private', max_length=10),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
