# Generated by Django 5.1.13 on 2025-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_experience_user_remove_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('user', 'Job Seeker'), ('recruiter', 'Recruiter')], default='user', help_text='Account type - cannot be changed after signup', max_length=10),
        ),
    ]
