# Generated by Django 5.0 on 2025-10-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_port',
            field=models.IntegerField(blank=True, default=587),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
