# Generated by Django 5.0 on 2025-10-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_latitude_userprofile_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
    ]
