# Generated by Django 5.0 on 2025-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Your contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_configured',
            field=models.BooleanField(default=False, help_text='Gmail is configured for sending emails'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Gmail App Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails', max_length=254, null=True),
        ),
    ]
