# Generated by Django 5.0 on 2025-10-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_email_verified_userprofile_email_and_more'),
        ('accounts', '0006_alter_userprofile_latitude_and_more'),
    ]

    operations = [
    ]
