# Generated by Django 5.1.13 on 2025-10-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='List of notable projects or portfolio work (comma-separated)', null=True),
        ),
    ]
