# Generated by Django 5.1.14 on 2025-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_url',
            field=models.URLField(blank=True, help_text='Any other professional link', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Your portfolio website URL', null=True),
        ),
    ]
