# Generated by Django 5.0 on 2025-11-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_github_url_userprofile_linkedin_url_and_more'),
        ('accounts', '0014_candidatematch'),
    ]

    operations = [
    ]
