# Generated by Django 5.0 on 2025-11-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20251124_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatematch',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.savedcandidatesearch'),
        ),
    ]
